namespace Microsoft.PointOfService
{
    public enum FiscalMessageType
    {
        Advance = 1,
        AdvancePaid = 2,
        AmountToBePaid = 3,
        AmountToBePaidBack = 4,
        Card = 5,
        CardNumber = 6,
        CardType = 7,
        Cash = 8,
        Cashier = 9,
        CashRegisterNumber = 10,
        Change = 11,
        Cheque = 12,
        ClientNumber = 13,
        ClientSignature = 14,
        CounterState = 15,
        CreditCard = 16,
        Currency = 17,
        CurrencyValue = 18,
        Deposit = 19,
        DepositReturned = 20,
        DotLine = 21,
        DriverNumber = 22,
        EmptyLine = 23,
        FreeText = 24,
        FreeTextWithDayLimit = 25,
        GivenDiscount = 26,
        LocalCredit = 27,
        MileageKilometers = 28,
        Note = 29,
        Paid = 30,
        PayIn = 31,
        PointGranted = 32,
        PointsBonus = 33,
        PointsReceipt = 34,
        PointsTotal = 35,
        Profited = 36,
        Rate = 37,
        RegisterNumber = 38,
        ShiftNumber = 39,
        StateOfAnAccount = 40,
        Subscription = 41,
        Table = 42,
        ThankYouForLoyalty = 43,
        TransactionNumber = 44,
        ValidTo = 45,
        Voucher = 46,
        VoucherPaid = 47,
        VoucherValue = 48,
        WithDiscount = 49,
        WithoutUplift = 50,
    }
}
