[assembly: System.Reflection.AssemblyVersionAttribute("1.12.0.0")]
[assembly: System.CLSCompliantAttribute(true)]
[assembly: System.Reflection.AssemblyCompanyAttribute("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProductAttribute("POS for .NET 1.12")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.12.1296.00")]
[assembly: System.Runtime.InteropServices.ComVisibleAttribute(false)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibilityAttribute]
[assembly: System.Runtime.CompilerServices.CompilationRelaxationsAttribute(8)]
[assembly: System.Reflection.AssemblyTitleAttribute("Microsoft.PointOfService")]
[assembly: System.Runtime.InteropServices.ClassInterfaceAttribute(System.Runtime.InteropServices.ClassInterfaceType.None)]
